version: '3.8'

services:
  gemini-synapse-app:
    # build: . 表示 Docker Compose 将使用当前目录下的 Dockerfile 来构建镜像
    build: .
    
    # 为容器指定一个固定的名字，方便管理
    container_name: gemini-synapse-app
    
    # 将主机的 8001 端口映射到容器的 8001 端口
    ports:
      - "8001:8001"
      
    # <<< 这是关键的修改 >>>
    # 数据卷挂载，实现数据持久化。
    # 我们挂载一个目录而不是单个文件，让 SQLite 可以自由地在其中创建数据库文件和临时文件。
    volumes:
      # 将主机当前目录下的 data 文件夹，映射到容器内的 /app/data 目录
      - ./data:/app/data
      
    # 从 .env 文件加载环境变量到容器中
    env_file:
      - .env
      
    # 配置重启策略
    # unless-stopped 表示除非手动停止容器，否则容器总是在退出后自动重启
    restart: unless-stopped
