services:
  gemini-synapse-app:
    build: .
    
    container_name: gemini-synapse-app
    
    ports:
      - "8008:8008"

    volumes:
      - ./data:/app/data
      
    env_file:
      - .env
      
    restart: unless-stopped
