version: '3.8'

services:
  gemini-synapse:
    # build: . 表示 Docker Compose 将使用当前目录下的 Dockerfile 来构建镜像
    build: .
    
    # 为容器指定一个固定的名字，方便管理
    container_name: gemini-synapse-app
    
    # 将主机的 8000 端口映射到容器的 8000 端口
    ports:
      - "8000:8000"
      
    # 数据卷挂载，实现数据持久化
    # 将主机当前目录下的 data.db 文件链接到容器内的 /app/data.db
    volumes:
      - ./data.db:/app/data.db
      
    # 从 .env 文件加载环境变量到容器中
    env_file:
      - .env
      
    # 配置重启策略
    # unless-stopped 表示除非手动停止容器，否则容器总是在退出后自动重启
    restart: unless-stopped